build:
  mode: s2i
  uri: https://github.com/wildfly/quickstart.git
  ref: 26.0.0.Final
  contextDir: microprofile-config
  s2i:
    featurePacks:
      - org.wildfly:wildfly-galleon-pack:26.1.1.Final
    galleonLayers:
      - jaxrs-server
      - microprofile-platform
deploy:
  replicas: 1
  env:
  - name: CONFIG_PROP
    value: Hello from OpenShift