build:
  mode: s2i
  uri: https://github.com/wildfly/quickstart.git
  ref: 26.0.0.Final
  contextDir: microprofile-config
  s2i:
    galleonLayers:
    - jaxrs-server
    - microprofile-platform
deploy:
  replicas: 1
  env:
  - name: CONFIG_PROP
    value: Hello from OpenShift